### ISSUE TITLE
Feature Request:  remove restrictions from `is_order_vars()`

### ISSUE THREAD

**Issue by kaz462** [pharmaverse/admiraldev#195]
### Feature Idea

To increase the flexibility of  `admiral::derive_var_obs_number()` as mentioned in https://github.com/pharmaverse/admiral/issues/1561 
could you help suggest if it's okay to remove `quo_is_desc_call()` from `is_order_vars()` ?  thank you :)

**Comment by bundfussr** [comment]
@kaz462 , thanks for creating this issue and apologies for not responding to your comment in https://github.com/pharmaverse/admiral/issues/1561.

In the beginning of admiral the `order` argument accepted arbitrary expressions. (The documentation still reflects this.) Then the team decided to only allow variables and `desc()` calls because of concerns that the function calls get too complicated if any expression could be specified. So the intention was to improve usability. However, there are use cases like your example where this restriction forces users to add work-arounds to their code. Usually you have to create a temporary variable before the admiral function call and remove it thereafter.

For the next release we want to clean-up the admiral functions to avoid overlaps and inconsistencies, and improve usability (https://github.com/pharmaverse/admiral/issues/1522). There we can also discuss this issue. If we lift the restriction, we should do it for all functions. I.e., the `order` argument should behave in the same way for all admiral functions.

I am currently working on creating a proposal for the clean-up. But this will take some time. It is unlikely that the admiral team can discuss it and take a decision this year.

**Comment by bundfussr** [comment]
@kaz462 , we have decided to allow expressions. I have created https://github.com/pharmaverse/admiral/issues/1727 as it does not affect `is_order_vars()` only.

**Comment by kaz462** [comment]
Thanks for following up, @bundfussr !

**Comment by bundfussr** [comment]
Covered by #241.
