### ISSUE TITLE
General Issue: Move deprecated arguments and functions to next phase or remove

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiraldev#459]
### Background Information

This one maybe is missing information and/or was not done correctly.  Will need some investigation.  Please reach out to me @bms63 for discussion before you start

![image](https://github.com/user-attachments/assets/b521f7fb-468b-4299-a7f0-2d9f726a629d)

### Definition of Done

- [ ] Functions or arguments being removed should be documented in the changelog
- [ ] Function or arguments being removed based on their phase of deprecation should also be documented
  - [ ] Bonus points if you split them up as Phase 1, 2, 3 so easier to track!
- [ ] Be sure functions/argument documents are appropriately updated and/or removed
- [ ] Be sure unit tests appropriately capture deprecation where appropriate
- [ ] Remove any old deprecation unit tests no longer relevant

@pharmaverse/admiral @pharmaverse/admiral_comm this is a good one to knock out!!  Very helpful to us to do this in the beginning of the cycle!

**Comment by StefanThoma** [comment]
Hi @sadchla-codes 
How is it going with this issue? 
I have finished these updates in {admiral}, it was pretty minimal.

**Comment by sadchla-codes** [comment]
> Hi @sadchla-codes How is it going with this issue? I have finished these updates in {admiral}, it was pretty minimal.

It's going ok, @bms63 @StefanThoma since this PR is not merged yet, should that exclude `quosures` from the list? Also, it looks like in some programs, that argument had a stop deprecated for some time, although I'm not a 100% certain at which version

![image](https://github.com/user-attachments/assets/28558826-a904-46f2-8994-a8237781a278)

**In quo.R file**
![image](https://github.com/user-attachments/assets/34ed6dd3-963c-4014-b823-b9df96df4a2a)

**in Changelog**
![image](https://github.com/user-attachments/assets/17ee5156-5c12-4eaf-b736-6cd1266d07ce)
