### ISSUE TITLE
General Issue: Increase test coverage for `warnings.R`

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiraldev#97]
### Background Information

We need to increase test coverage for our functions. The below screenshot has the function and gap in test coverage that we need to write additional unit tests

![image](https://user-images.githubusercontent.com/10111024/191829213-c5d214f9-76de-4d54-9c1b-9f1396fdd82b.png)

### Definition of Done

Unit tests are written that increase the coverage of the warnings.R file

You can get this report by running devtools::test_coverage()

**Comment by bms63** [comment]
Hi @PoojaKumari05  will you be able to complete this issue in the 14+ days?

**Comment by PoojaKumari05** [comment]
> Hi @PoojaKumari05 will you be able to complete this issue in the 14+ days?
@bms63 - yes will wrap this up by next week

**Comment by PoojaKumari05** [comment]
@bms63 - Hi ben, I am getting the following error when I try to run devtools::test_coverage(), I initially thought that something broke in my RStudio project, so I created a new project, but since I am currently using the free version it crashed when I tried to run renv::restore(). So I went ahead a install RStudio desktop and tried to create a new project, but unfortunately I am getting the same error now as well. Does this seem familiar to you?  
![image](https://user-images.githubusercontent.com/90273880/203958135-803109d5-d403-4d8e-96d1-a1b922af62a3.png)

**Comment by PoojaKumari05** [comment]
Hi @bms63 - Any suggestions on how to write a test case for the following:


![Image](https://user-images.githubusercontent.com/90273880/220572542-948b667b-2255-4ed1-b426-4d0bd5751f95.png)

**Comment by bms63** [comment]
I do not. 

 @pharmaverse/admiral any ideas.

**Comment by bundfussr** [comment]
Maybe `suppress_warning(as.integer("a"), regexpr = "coercion")`?

**Comment by PoojaKumari05** [comment]
> Maybe `suppress_warning(as.integer("a"), regexpr = "coercion")`?

Hi @bundfussr - Thankyou for the suggestion. :) I added expect_equal() in the test case and now have 100% test coverage, earlier I was only verifying using expect_warning().
